### Introduction to Week 2
This week, we will look a little more into manipulating string and numerical variables. 

For the second half of the lesson, we will look at some more data structures (tuples and dictionaries) and control flows, indexing, and list comprehensions. 

We will close it out by looking at how Libraries work, and some basic file handling.

### Part 1: Manipulating String and Numerical Variables

#### Part 1.1 Let's start with some basic string operations

In [ ]:
# this is a string. It can be assigned to a variable. 
my_string = 'I am a string. Humans can interpret me easily'

In [61]:
# We can print this string as follows:
print(my_string)

I am a string. Humans can interpret me easily


In [10]:
# Split - split splits a string on the character provided. It turns the string into a list containing bits of the original 
# string, split where the character was
print(my_string.split('.'))

['I am a string', ' Humans can interpret me easily']


In [62]:
# we can use this to access just part of the string, e.g.:
list_of_split_up_parts = my_string.split('. ')
print(list_of_split_up_parts[1])

Humans can interpret me easily


In [63]:
print(list_of_split_up_parts[0])

I am a string


In [15]:
# strings are iterable - we can print certain letters or chunks, depending on how we index them:
print(my_string[0])
print(my_string[3])

I
m


In [17]:
print(my_string[0:15])

I am a string. 


In [18]:
for q in range(0, 15):
    print(my_string[q:15])

I am a string. 
 am a string. 
am a string. 
m a string. 
 a string. 
a string. 
 string. 
string. 
tring. 
ring. 
ing. 
ng. 
g. 
. 
 


In [20]:
for q in range(0, 15):
    print(my_string[15:-q])


Humans can interpret me easil
Humans can interpret me easi
Humans can interpret me eas
Humans can interpret me ea
Humans can interpret me e
Humans can interpret me 
Humans can interpret me
Humans can interpret m
Humans can interpret 
Humans can interpret
Humans can interpre
Humans can interpr
Humans can interp
Humans can inter


In [71]:
# Replacement operations are handy too. This operation can be chained for entertainment value:
print(my_string)
new_string = my_string.replace("I am","Nicholas is").replace("string", "human").replace("Humans", "Other humans").replace("me","him")
print(new_string)
print(new_string.replace('Nicholas', 'Charles').replace('easily','from time to time'))

I am a string. Humans can interpret me easily
Nicholas is a human. Other humans can interpret him easily
Charles is a human. Other humans can interpret him from time to time


In [72]:
# Strings can also be added
add_chunk = '. I love strings'
my_string + add_chunk

'I am a string. Humans can interpret me easily. I love strings'

In [73]:
#... but not subtracted:

In [74]:
subtract_bit = 'easily.'
my_string - subtract_bit

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [50]:
# the backslash is special in strings - it is called an escape character. 
# It does a number of different things depending on the next letter:

In [51]:
print('using \n generates a new line!')

using 
 generates a new line!


In [57]:
print('using \t generates a tab!')

using 	 generates a tab!


In [53]:
print('using \t\t\t\t\t generates a load of tabs!')

using 					 generates a load of tabs!


In [58]:
# you can tell python to ignore this by adding 'r' to the start of a string. This prevents escapes from working
# (and prevents you from attemptingn escape when you didn't mean to - e.g. in file paths)

In [59]:
string_will_fail = 'C:\Users\charl\Documents\CE\RAM\OneDrive_1_3-6-2019\QXN\RN'

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-59-e2aff5cf5a16>, line 1)

In [60]:
string_will_work = r'C:\Users\charl\Documents\CE\RAM\OneDrive_1_3-6-2019\QXN\RN'

In [99]:
# formatting strings with variables is very useful. There are many options for this
fave_number = 10
t = 'my favourite number is: %f' % fave_number
print(t)

import time 
the_time = time.ctime()
print('\nthe date and time is currently: %s' % the_time)

my favourite number is: 10.000000

the date and time is currently: Fri Mar  8 12:10:08 2019


In [112]:
# be aware of the letter after the percent sign - it changes the nature of the string formatting:
q = 12 / 5

print('%d' % q)
print('%f' % q)
print('%e' % q)
print('%s' % q)

2
2.400000
2.400000e+00
2.4


In [107]:
"""
THE FULL LIST - A REFERENCE GUIDE - https://python-reference.readthedocs.io/en/latest/docs/str/formatting.html 
‘d’
Signed integer decimal.
‘i’
Signed integer decimal.
‘o’
Signed octal value. The alternate form causes a leading zero (‘0’) to be inserted between left-hand padding and the formatting of the number if the leading character of the result is not already a zero.
‘u’
Obsolete type – it is identical to ‘d’. See PEP 237.
‘x’ or ‘X’
Signed hexadecimal. The alternate form causes a leading ‘0x’ or ‘0X’ (depending on whether the ‘x’ or ‘X’ format was used) to be inserted between left-hand padding and the formatting of the number if the leading character of the result is not already a zero.
‘e’ or ‘E’
Floating point exponential format. The alternate form causes the result to always contain a decimal point, even if no digits follow it.

The precision determines the number of digits after the decimal point and defaults to 6.

‘f’ or ‘F’
Floating point decimal format. The alternate form causes the result to always contain a decimal point, even if no digits follow it.

The precision determines the number of digits after the decimal point and defaults to 6.

‘g’ or ‘G’
Floating point format. Uses exponential format if exponent is less than -4 or not less than precision, decimal format otherwise. The alternate form causes the result to always contain a decimal point, and trailing zeroes are not removed as they would otherwise be.

The precision determines the number of significant digits before and after the decimal point and defaults to 6.

‘c’
Single character (accepts integer or single character string).
‘r’
String (converts any Python object using repr()).

The precision determines the maximal number of characters used.

‘s’
String (converts any Python object using str()).

If the object or format provided is a unicode string, the resulting string will also be unicode.

The precision determines the maximal number of characters used.

‘%’
No argument is converted, results in a ‘%’ character in the result.
"""

'\nTHE FULL LIST - A REFERENCE GUIDE\n‘d’\nSigned integer decimal.\n‘i’\nSigned integer decimal.\n‘o’\nSigned octal value. The alternate form causes a leading zero (‘0’) to be inserted between left-hand padding and the formatting of the number if the leading character of the result is not already a zero.\n‘u’\nObsolete type – it is identical to ‘d’. See PEP 237.\n‘x’ or ‘X’\nSigned hexadecimal. The alternate form causes a leading ‘0x’ or ‘0X’ (depending on whether the ‘x’ or ‘X’ format was used) to be inserted between left-hand padding and the formatting of the number if the leading character of the result is not already a zero.\n‘e’ or ‘E’\nFloating point exponential format. The alternate form causes the result to always contain a decimal point, even if no digits follow it.\n\nThe precision determines the number of digits after the decimal point and defaults to 6.\n\n‘f’ or ‘F’\nFloating point decimal format. The alternate form causes the result to always contain a decimal point, even

#### Part 1.2: Numerical variables

In [76]:
# we can also set a variable equal to a number
a = 1

In [77]:
print(a)

1


In [78]:
# We can use this fact to do basic mathematical operations. Addition:
b = 3
c = a + b
print(c)

4


In [80]:
# subtraction
d = b - a
print(d)

2


In [82]:
# multiplication
e = d * c
print(e)

8


In [85]:
# division
f = e / b
print(f)

2.6666666666666665


In [89]:
# finding the remainder of a division:
g = e % b
print('the remainder of %s divided by %s is %s' % (e, b, g))

the remainder of 8 divided by 3 is 2


In [94]:
# raising items to the power of another item
print(e)
print(b)
print('%s cubed is %s' % (e, e ** b))

8
3
8 cubed is 512


In [113]:
# we can start to do more fancy operations with numpy, e.g. matrix math
import numpy as np

In [115]:
Arr1 = np.array([[3,4,5],[5,7,8]])

In [116]:
Arr1

array([[3, 4, 5],
       [5, 7, 8]])

In [128]:
Arr2 = np.array([[2,2,2],[2,2,2]])
Arr2 * Arr1

array([[ 6,  8, 10],
       [10, 14, 16]])

In [ ]:
# arrays need to be the same shape to be broadcast together. For that, we can use commands like reshape / transpose

In [117]:
Arr2 = np.array([[1,2],[8,7],[5,7]])

In [118]:
Arr2

array([[1, 2],
       [8, 7],
       [5, 7]])

In [122]:
Arr1 * Arr2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [123]:
Arr2 = Arr2.transpose()

In [124]:
Arr2

array([[1, 8, 5],
       [2, 7, 7]])

In [127]:
Arr2 * Arr1

array([[ 3, 32, 25],
       [10, 49, 56]])

In [129]:
# Generate a frame of all zeroes with np.zeros()
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [135]:
# Populate the numpy array with (x,y) style indexing. Note - it is flipped! rows first then columns
empty_frame = np.zeros([3,3])
empty_frame

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [134]:
empty_frame[2][2] = 9
empty_frame[0][2] = 4
empty_frame

array([[0., 0., 4.],
       [0., 0., 0.],
       [0., 0., 9.]])

### Part 2: Data Structures II: Tuples, Lists II, Dictionaries

#### Part 2.1: Tuples

In [146]:
# tuples are a fundamental data structure. They are data, contained within parantheses
I_am_tuple = (4,5)
I_am_also_a_tuple = ('apex','legend')

In [138]:
# They can have more than 2 elements:
mega_tuple = (4,5,6,7,8,9)

In [139]:
# you can reference within them:
mega_tuple[0]

4

In [141]:
mega_tuple[3]

7

In [140]:
mega_tuple[-1]

9

In [142]:
# 'tuples' are immutable. This means you can't edit them. 
mega_tuple[0] = 7

TypeError: 'tuple' object does not support item assignment

In [148]:
# They are iterable, however:
for i in mega_tuple:
    print(i)

4
5
6
7
8
9


In [ ]:
# The numerical ordering of tuples can be quite a useful property, if data is stored in a regular way. 
# Let's make a small phone book example

In [162]:
Frodo = ('Frodo','+202 569 8745','frodo@baggins_shire.com')
Sam = ('Sam', '+202 456 5646', 'sam@samwise_gamgee.com')

In [163]:
# Let's print just the people's names:
for person in [Frodo, Sam]:
    print(person[0])

Frodo
Sam


In [164]:
# Let's print just the people's emails:
for person in [Frodo, Sam]:
    print(person[2])

frodo@baggins_shire.com
sam@samwise_gamgee.com


In [165]:
# Let's print out s formatted string:
for person in [Frodo, Sam]:
    print('My name is %s, and you can call me on %s or email me at %s' % (person[0], person[1], person[2]))

My name is Frodo, and you can call me on +202 569 8745 or email me at frodo@baggins_shire.com
My name is Sam, and you can call me on +202 456 5646 or email me at sam@samwise_gamgee.com


#### Part 2.2 Lists II

#### Part 2.3: Dictionaries

In [ ]:
# A dictionary is another fundamental data structure. The value of a dictionary is the ('key':'value') organisation, much like
# a standard dictionary!

In [169]:
fellowship = {'hobbit_1':'Frodo',
             'hobbit_2':'Sam',
             'hobbit_3':'Pippin',
             'hobbit_4':'Merry'}

In [170]:
# we can call the values from the keys:
fellowship['hobbit_1']

'Frodo'

In [172]:
# we can also generate lists of both the keys:
fellowship.keys()

dict_keys(['hobbit_1', 'hobbit_2', 'hobbit_3', 'hobbit_4'])

In [173]:
# ...and the values:
fellowship.values()

dict_values(['Frodo', 'Sam', 'Pippin', 'Merry'])

In [176]:
# we can store complex objects in the dictionary in nested structure
fellowship_contact_info = {'Frodo':Frodo,
                          'Sam':Sam}

In [177]:
fellowship_contact_info['Frodo']

('Frodo', '+202 569 8745', 'frodo@baggins_shire.com')

In [178]:
# We can also reference objects within objects:
fellowship_contact_info['Frodo'][2]

'frodo@baggins_shire.com'

In [179]:
# remember that the components of this dictionary are tuples.
# alternatively, we could use dictionaries of dictionaries:

Frodo = {'name':'Frodo','cell':'+202 569 8745','email':'frodo@baggins_shire.com'}
Sam = {'name':'Sam','cell':'+202 456 5646','email':'sam@samwise_gamgee.com'}

# Put reformatted dicts into the contact_info dict instead of the tuples
fellowship_contact_info = {'Frodo':Frodo,
                          'Sam':Sam}

In [182]:
fellowship_contact_info['Sam']

{'name': 'Sam', 'cell': '+202 456 5646', 'email': 'sam@samwise_gamgee.com'}

In [183]:
fellowship_contact_info['Sam']['cell']

'+202 456 5646'

In [186]:
fellowship_contact_info['Sam']['email']

'sam@samwise_gamgee.com'

In [ ]:
# This is actually the structure of a JSON file - which is organized as a dictionary of nested dictionaries!

### Part 3: Libraries and File Handling